/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as MpesaCallbackRouteImport } from './routes/mpesa.callback'
import { Route as C2bValidationRouteImport } from './routes/c2b.validation'
import { Route as C2bConfirmationRouteImport } from './routes/c2b.confirmation'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MpesaCallbackRoute = MpesaCallbackRouteImport.update({
  id: '/mpesa/callback',
  path: '/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const C2bValidationRoute = C2bValidationRouteImport.update({
  id: '/c2b/validation',
  path: '/c2b/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const C2bConfirmationRoute = C2bConfirmationRouteImport.update({
  id: '/c2b/confirmation',
  path: '/c2b/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/customers': typeof AppCustomersRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/c2b/confirmation': typeof C2bConfirmationRoute
  '/c2b/validation': typeof C2bValidationRoute
  '/mpesa/callback': typeof MpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/customers': typeof AppCustomersRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/c2b/confirmation': typeof C2bConfirmationRoute
  '/c2b/validation': typeof C2bValidationRoute
  '/mpesa/callback': typeof MpesaCallbackRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/c2b/confirmation': typeof C2bConfirmationRoute
  '/c2b/validation': typeof C2bValidationRoute
  '/mpesa/callback': typeof MpesaCallbackRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/analytics'
    | '/customers'
    | '/payments'
    | '/settings'
    | '/c2b/confirmation'
    | '/c2b/validation'
    | '/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/analytics'
    | '/customers'
    | '/payments'
    | '/settings'
    | '/c2b/confirmation'
    | '/c2b/validation'
    | '/mpesa/callback'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/login'
    | '/_app/analytics'
    | '/_app/customers'
    | '/_app/payments'
    | '/_app/settings'
    | '/c2b/confirmation'
    | '/c2b/validation'
    | '/mpesa/callback'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  C2bConfirmationRoute: typeof C2bConfirmationRoute
  C2bValidationRoute: typeof C2bValidationRoute
  MpesaCallbackRoute: typeof MpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/mpesa/callback': {
      id: '/mpesa/callback'
      path: '/mpesa/callback'
      fullPath: '/mpesa/callback'
      preLoaderRoute: typeof MpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2b/validation': {
      id: '/c2b/validation'
      path: '/c2b/validation'
      fullPath: '/c2b/validation'
      preLoaderRoute: typeof C2bValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2b/confirmation': {
      id: '/c2b/confirmation'
      path: '/c2b/confirmation'
      fullPath: '/c2b/confirmation'
      preLoaderRoute: typeof C2bConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  C2bConfirmationRoute: C2bConfirmationRoute,
  C2bValidationRoute: C2bValidationRoute,
  MpesaCallbackRoute: MpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
